Class otzi.core.vo.Template.Property Extends otzi.core.vo.Template.NameValue
{

Property Index As %String;

Property List As %String;

Property Parameters As list Of otzi.core.vo.Template.Parameter;

Storage Default
{
<Data name="NameValueState">
<Value name="1">
<Value>Name</Value>
</Value>
<Value name="2">
<Value>Value</Value>
</Value>
<Value name="3">
<Value>Index</Value>
</Value>
<Value name="4">
<Value>List</Value>
</Value>
<Value name="5">
<Value>Parameters</Value>
</Value>
</Data>
<Type>%Library.CacheSerialState</Type>
}

}

